<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 5 Testing our first hypothesis | UNSW PSYC2001 Computing Tutorials</title>
  <meta name="description" content="This book contains the complete guide for computing tutorials for PSYC2001 at UNSW." />
  <meta name="generator" content="bookdown 0.37 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 5 Testing our first hypothesis | UNSW PSYC2001 Computing Tutorials" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This book contains the complete guide for computing tutorials for PSYC2001 at UNSW." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 5 Testing our first hypothesis | UNSW PSYC2001 Computing Tutorials" />
  
  <meta name="twitter:description" content="This book contains the complete guide for computing tutorials for PSYC2001 at UNSW." />
  

<meta name="author" content="Bart Cooley, Peter Lovibond, Kelly Garner" />


<meta name="date" content="2025-10-01" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="what-is-the-sampling-distribution-of-the-mean.html"/>
<link rel="next" href="testing-between-groups.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">UNSW PSYC2001 Computing Tutorials</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> url: your book url like https://bookdown.org/yihui/bookdown</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#the-purpose-of-this-coursebook"><i class="fa fa-check"></i><b>1.1</b> The purpose of this coursebook</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#structure-of-the-coursebook"><i class="fa fa-check"></i><b>1.2</b> Structure of the Coursebook</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#to-do"><i class="fa fa-check"></i><b>1.3</b> To-do</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="introduction-to-r.html"><a href="introduction-to-r.html"><i class="fa fa-check"></i><b>2</b> Introduction to R</a>
<ul>
<li class="chapter" data-level="2.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#r-and-r-studio"><i class="fa fa-check"></i><b>2.1</b> R and R Studio</a></li>
<li class="chapter" data-level="2.2" data-path="introduction-to-r.html"><a href="introduction-to-r.html#getting-started"><i class="fa fa-check"></i><b>2.2</b> Getting started</a></li>
<li class="chapter" data-level="2.3" data-path="introduction-to-r.html"><a href="introduction-to-r.html#getting-to-know-r-studio"><i class="fa fa-check"></i><b>2.3</b> Getting to know R Studio</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#activity---using-the-console"><i class="fa fa-check"></i><b>2.3.1</b> Activity - using the console</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="introduction-to-r.html"><a href="introduction-to-r.html#scripts"><i class="fa fa-check"></i><b>2.4</b> Scripts</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#activity---getting-to-know-scripts"><i class="fa fa-check"></i><b>2.4.1</b> Activity - Getting to know scripts</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="introduction-to-r.html"><a href="introduction-to-r.html#functions-and-arguments"><i class="fa fa-check"></i><b>2.5</b> Functions and arguments</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#activity---using-a-function"><i class="fa fa-check"></i><b>2.5.1</b> Activity - using a function</a></li>
<li class="chapter" data-level="2.5.2" data-path="introduction-to-r.html"><a href="introduction-to-r.html#argument-names"><i class="fa fa-check"></i><b>2.5.2</b> Argument names</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="introduction-to-r.html"><a href="introduction-to-r.html#base-r-and-packages"><i class="fa fa-check"></i><b>2.6</b> Base R and packages</a></li>
<li class="chapter" data-level="2.7" data-path="introduction-to-r.html"><a href="introduction-to-r.html#installing-and-loading-packages"><i class="fa fa-check"></i><b>2.7</b> Installing and loading packages</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#activity-install-the-tidyverse"><i class="fa fa-check"></i><b>2.7.1</b> Activity: Install the tidyverse</a></li>
<li class="chapter" data-level="2.7.2" data-path="introduction-to-r.html"><a href="introduction-to-r.html#activity-load-the-tidyverse"><i class="fa fa-check"></i><b>2.7.2</b> Activity: Load the tidyverse</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="introduction-to-r.html"><a href="introduction-to-r.html#objects"><i class="fa fa-check"></i><b>2.8</b> Objects</a>
<ul>
<li class="chapter" data-level="2.8.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#activity-create-some-objects"><i class="fa fa-check"></i><b>2.8.1</b> Activity: Create some objects</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="introduction-to-r.html"><a href="introduction-to-r.html#datatypes"><i class="fa fa-check"></i><b>2.9</b> Datatypes</a></li>
<li class="chapter" data-level="2.10" data-path="introduction-to-r.html"><a href="introduction-to-r.html#looking-after-the-environment"><i class="fa fa-check"></i><b>2.10</b> Looking after the environment</a></li>
<li class="chapter" data-level="2.11" data-path="introduction-to-r.html"><a href="introduction-to-r.html#the-power-of-scripts"><i class="fa fa-check"></i><b>2.11</b> The power of scripts</a>
<ul>
<li class="chapter" data-level="2.11.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#final-activity-run-the-script"><i class="fa fa-check"></i><b>2.11.1</b> Final Activity: Run the script</a></li>
</ul></li>
<li class="chapter" data-level="2.12" data-path="introduction-to-r.html"><a href="introduction-to-r.html#you-are-free"><i class="fa fa-check"></i><b>2.12</b> You are Free!</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html"><i class="fa fa-check"></i><b>3</b> Data wrangling and visualisation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#checking-installation-and-loading-packages"><i class="fa fa-check"></i><b>3.1</b> Checking installation and loading packages</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#activity-load-your-packages"><i class="fa fa-check"></i><b>3.1.1</b> Activity: Load your packages</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#what-do-packages-do"><i class="fa fa-check"></i><b>3.2</b> What do packages do?</a></li>
<li class="chapter" data-level="3.3" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#what-do-these-packages-do"><i class="fa fa-check"></i><b>3.3</b> What do these packages do?</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#activity-find-out-about-packages"><i class="fa fa-check"></i><b>3.3.1</b> Activity: find out about packages</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#organisation-and-csv-files"><i class="fa fa-check"></i><b>3.4</b> Organisation and CSV files</a></li>
<li class="chapter" data-level="3.5" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#importing-your-data-in-r"><i class="fa fa-check"></i><b>3.5</b> Importing your Data in R</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#sec-import-data"><i class="fa fa-check"></i><b>3.5.1</b> Activity: Import the data</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#having-a-look-at-our-imported-data"><i class="fa fa-check"></i><b>3.6</b> Having a look at our imported data</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#sec-data-view"><i class="fa fa-check"></i><b>3.6.1</b> Activity: View the data. Always, always, view the data.</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#checking-the-quality-of-our-data"><i class="fa fa-check"></i><b>3.7</b> Checking the quality of our data</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#activity-summarise-the-data"><i class="fa fa-check"></i><b>3.7.1</b> Activity: Summarise the data</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#cleaning-the-data"><i class="fa fa-check"></i><b>3.8</b> Cleaning the data</a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#activity-find-and-replace--999-values"><i class="fa fa-check"></i><b>3.8.1</b> Activity: Find and replace <code>-999</code> values</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#introducing-piping"><i class="fa fa-check"></i><b>3.9</b> Introducing Piping</a>
<ul>
<li class="chapter" data-level="3.9.1" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#activity-pipe-with-pipes"><i class="fa fa-check"></i><b>3.9.1</b> Activity: Pipe with pipes</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#exporting-data"><i class="fa fa-check"></i><b>3.10</b> Exporting Data</a>
<ul>
<li class="chapter" data-level="3.10.1" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#activity-save-the-cleaned-data"><i class="fa fa-check"></i><b>3.10.1</b> Activity: Save the cleaned data</a></li>
</ul></li>
<li class="chapter" data-level="3.11" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#data-visualization-using-ggplot2"><i class="fa fa-check"></i><b>3.11</b> Data visualization using <code>ggplot2</code></a>
<ul>
<li class="chapter" data-level="3.11.1" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#activity-create-a-boxplot-in-ggplot"><i class="fa fa-check"></i><b>3.11.1</b> Activity: Create a boxplot in <code>ggplot()</code></a></li>
<li class="chapter" data-level="3.11.2" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#activity-more-data-viz-more-better---creating-a-histogram-in-ggplot"><i class="fa fa-check"></i><b>3.11.2</b> Activity: More data-viz, more better - Creating a histogram in <code>ggplot()</code></a></li>
</ul></li>
<li class="chapter" data-level="3.12" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#you-are-free-1"><i class="fa fa-check"></i><b>3.12</b> You are Free!</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="what-is-the-sampling-distribution-of-the-mean.html"><a href="what-is-the-sampling-distribution-of-the-mean.html"><i class="fa fa-check"></i><b>4</b> What is the sampling distribution of the mean</a>
<ul>
<li class="chapter" data-level="4.1" data-path="what-is-the-sampling-distribution-of-the-mean.html"><a href="what-is-the-sampling-distribution-of-the-mean.html#checking-installation-and-loading-packages-1"><i class="fa fa-check"></i><b>4.1</b> Checking installation and loading packages</a></li>
<li class="chapter" data-level="4.2" data-path="what-is-the-sampling-distribution-of-the-mean.html"><a href="what-is-the-sampling-distribution-of-the-mean.html#sampling-distribution-of-the-mean"><i class="fa fa-check"></i><b>4.2</b> Sampling distribution of the mean</a></li>
<li class="chapter" data-level="4.3" data-path="what-is-the-sampling-distribution-of-the-mean.html"><a href="what-is-the-sampling-distribution-of-the-mean.html#checking-the-mean-of-time_on_social-from-last-week"><i class="fa fa-check"></i><b>4.3</b> Checking the mean of <code>time_on_social</code> from last week</a></li>
<li class="chapter" data-level="4.4" data-path="what-is-the-sampling-distribution-of-the-mean.html"><a href="what-is-the-sampling-distribution-of-the-mean.html#activity-1---reading-in-data"><i class="fa fa-check"></i><b>4.4</b> Activity 1 - Reading in Data</a></li>
<li class="chapter" data-level="4.5" data-path="what-is-the-sampling-distribution-of-the-mean.html"><a href="what-is-the-sampling-distribution-of-the-mean.html#checking-the-unsw-value-in-this-dataset."><i class="fa fa-check"></i><b>4.5</b> Checking the UNSW value in this dataset.</a></li>
<li class="chapter" data-level="4.6" data-path="what-is-the-sampling-distribution-of-the-mean.html"><a href="what-is-the-sampling-distribution-of-the-mean.html#activity-2---finding-the-university-of-sydney"><i class="fa fa-check"></i><b>4.6</b> Activity 2 - Finding the University of Sydney</a></li>
<li class="chapter" data-level="4.7" data-path="what-is-the-sampling-distribution-of-the-mean.html"><a href="what-is-the-sampling-distribution-of-the-mean.html#vectors-and-the-sample-function"><i class="fa fa-check"></i><b>4.7</b> Vectors and the sample function</a></li>
<li class="chapter" data-level="4.8" data-path="what-is-the-sampling-distribution-of-the-mean.html"><a href="what-is-the-sampling-distribution-of-the-mean.html#what-does-the-sampling-distribution-of-the-mean-look-like-with-only-a-few-samples"><i class="fa fa-check"></i><b>4.8</b> What does the sampling distribution of the mean look like with only a few samples ?</a></li>
<li class="chapter" data-level="4.9" data-path="what-is-the-sampling-distribution-of-the-mean.html"><a href="what-is-the-sampling-distribution-of-the-mean.html#what-does-the-sampling-distribution-of-the-mean-look-like-as-we-add-more-samples"><i class="fa fa-check"></i><b>4.9</b> What does the sampling distribution of the mean look like as we add more samples?</a></li>
<li class="chapter" data-level="4.10" data-path="what-is-the-sampling-distribution-of-the-mean.html"><a href="what-is-the-sampling-distribution-of-the-mean.html#activity-3---increasing-the-sample-size"><i class="fa fa-check"></i><b>4.10</b> Activity 3 - Increasing the sample size</a></li>
<li class="chapter" data-level="4.11" data-path="what-is-the-sampling-distribution-of-the-mean.html"><a href="what-is-the-sampling-distribution-of-the-mean.html#activity-4---visualising-the-sampling-distribution-of-the-mean-with-increasing-samples"><i class="fa fa-check"></i><b>4.11</b> Activity 4 - Visualising the sampling distribution of the mean with increasing samples</a></li>
<li class="chapter" data-level="4.12" data-path="what-is-the-sampling-distribution-of-the-mean.html"><a href="what-is-the-sampling-distribution-of-the-mean.html#extension---what-happens-to-a-the-sampling-distribution-of-the-mean-for-other-population-distributions"><i class="fa fa-check"></i><b>4.12</b> Extension - What happens to a the sampling distribution of the mean for other population distributions ?</a></li>
<li class="chapter" data-level="4.13" data-path="what-is-the-sampling-distribution-of-the-mean.html"><a href="what-is-the-sampling-distribution-of-the-mean.html#you-are-free-2"><i class="fa fa-check"></i><b>4.13</b> You are Free!</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="testing-our-first-hypothesis.html"><a href="testing-our-first-hypothesis.html"><i class="fa fa-check"></i><b>5</b> Testing our first hypothesis</a>
<ul>
<li class="chapter" data-level="5.1" data-path="testing-our-first-hypothesis.html"><a href="testing-our-first-hypothesis.html#checking-installation-and-loading-packages-2"><i class="fa fa-check"></i><b>5.1</b> Checking installation and loading packages</a></li>
<li class="chapter" data-level="5.2" data-path="testing-our-first-hypothesis.html"><a href="testing-our-first-hypothesis.html#developing-our-hypotheses"><i class="fa fa-check"></i><b>5.2</b> Developing our hypotheses</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="testing-our-first-hypothesis.html"><a href="testing-our-first-hypothesis.html#activity---defining-our-hypotheses"><i class="fa fa-check"></i><b>5.2.1</b> Activity - Defining our hypotheses</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="testing-our-first-hypothesis.html"><a href="testing-our-first-hypothesis.html#visualising-our-data"><i class="fa fa-check"></i><b>5.3</b> Visualising our data</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="testing-our-first-hypothesis.html"><a href="testing-our-first-hypothesis.html#activity---loading-in-the-data"><i class="fa fa-check"></i><b>5.3.1</b> Activity - Loading in the data</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="testing-our-first-hypothesis.html"><a href="testing-our-first-hypothesis.html#density-plots-are-useful-and-pretty"><i class="fa fa-check"></i><b>5.4</b> Density plots are useful (and pretty)</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="testing-our-first-hypothesis.html"><a href="testing-our-first-hypothesis.html#activity---get-back-on-the-pipes"><i class="fa fa-check"></i><b>5.4.1</b> Activity - Get back on the pipes!</a></li>
<li class="chapter" data-level="5.4.2" data-path="testing-our-first-hypothesis.html"><a href="testing-our-first-hypothesis.html#activity---start-plotting"><i class="fa fa-check"></i><b>5.4.2</b> Activity - start plotting</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="testing-our-first-hypothesis.html"><a href="testing-our-first-hypothesis.html#activity-2---choosing-a-new-theme"><i class="fa fa-check"></i><b>5.5</b> Activity 2 - Choosing a new theme</a></li>
<li class="chapter" data-level="5.6" data-path="testing-our-first-hypothesis.html"><a href="testing-our-first-hypothesis.html#descriptive-statistics"><i class="fa fa-check"></i><b>5.6</b> Descriptive statistics</a></li>
<li class="chapter" data-level="5.7" data-path="testing-our-first-hypothesis.html"><a href="testing-our-first-hypothesis.html#activity-3---calculating-the-median-number-of-likes"><i class="fa fa-check"></i><b>5.7</b> Activity 3 - Calculating the median number of likes</a></li>
<li class="chapter" data-level="5.8" data-path="testing-our-first-hypothesis.html"><a href="testing-our-first-hypothesis.html#testing-hypotheses-manually"><i class="fa fa-check"></i><b>5.8</b> Testing hypotheses manually</a></li>
<li class="chapter" data-level="5.9" data-path="testing-our-first-hypothesis.html"><a href="testing-our-first-hypothesis.html#testing-hypothesis-using-a-two-sample-t-test"><i class="fa fa-check"></i><b>5.9</b> Testing hypothesis using a two-sample t-test</a></li>
<li class="chapter" data-level="5.10" data-path="testing-our-first-hypothesis.html"><a href="testing-our-first-hypothesis.html#activity-4---one-sample-t-tests"><i class="fa fa-check"></i><b>5.10</b> Activity 4 - One-sample t-tests</a></li>
<li class="chapter" data-level="5.11" data-path="testing-our-first-hypothesis.html"><a href="testing-our-first-hypothesis.html#writing-up-results-and-conclusions"><i class="fa fa-check"></i><b>5.11</b> Writing up results and conclusions</a></li>
<li class="chapter" data-level="5.12" data-path="testing-our-first-hypothesis.html"><a href="testing-our-first-hypothesis.html#plotting-our-results"><i class="fa fa-check"></i><b>5.12</b> Plotting our results</a></li>
<li class="chapter" data-level="5.13" data-path="testing-our-first-hypothesis.html"><a href="testing-our-first-hypothesis.html#activity-5---plotting-the-mean-number-of-likes"><i class="fa fa-check"></i><b>5.13</b> Activity 5 - Plotting the mean number of likes</a></li>
<li class="chapter" data-level="5.14" data-path="testing-our-first-hypothesis.html"><a href="testing-our-first-hypothesis.html#you-are-free-3"><i class="fa fa-check"></i><b>5.14</b> You are Free!</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="testing-between-groups.html"><a href="testing-between-groups.html"><i class="fa fa-check"></i><b>6</b> Testing between groups</a>
<ul>
<li class="chapter" data-level="6.1" data-path="testing-between-groups.html"><a href="testing-between-groups.html#checking-installation-and-loading-packages-3"><i class="fa fa-check"></i><b>6.1</b> Checking installation and loading packages</a></li>
<li class="chapter" data-level="6.2" data-path="testing-between-groups.html"><a href="testing-between-groups.html#testing-between-groups-1"><i class="fa fa-check"></i><b>6.2</b> Testing between groups</a></li>
<li class="chapter" data-level="6.3" data-path="testing-between-groups.html"><a href="testing-between-groups.html#activity-1---formulate-your-research-question"><i class="fa fa-check"></i><b>6.3</b> Activity 1 - Formulate your research question</a></li>
<li class="chapter" data-level="6.4" data-path="testing-between-groups.html"><a href="testing-between-groups.html#activity-2---creating-our-likes-variable"><i class="fa fa-check"></i><b>6.4</b> Activity 2 - Creating our likes variable</a></li>
<li class="chapter" data-level="6.5" data-path="testing-between-groups.html"><a href="testing-between-groups.html#wrangling-our-data"><i class="fa fa-check"></i><b>6.5</b> Wrangling our data</a></li>
<li class="chapter" data-level="6.6" data-path="testing-between-groups.html"><a href="testing-between-groups.html#activity-3---visualising-our-data-before-analysis"><i class="fa fa-check"></i><b>6.6</b> Activity 3 - Visualising our data before analysis</a></li>
<li class="chapter" data-level="6.7" data-path="testing-between-groups.html"><a href="testing-between-groups.html#activity-4---visualising-group-differences"><i class="fa fa-check"></i><b>6.7</b> Activity 4 - Visualising group differences</a></li>
<li class="chapter" data-level="6.8" data-path="testing-between-groups.html"><a href="testing-between-groups.html#activity-5---descriptive-statistics"><i class="fa fa-check"></i><b>6.8</b> Activity 5 - Descriptive statistics</a></li>
<li class="chapter" data-level="6.9" data-path="testing-between-groups.html"><a href="testing-between-groups.html#independent-samples-t-test"><i class="fa fa-check"></i><b>6.9</b> Independent samples t-test</a></li>
<li class="chapter" data-level="6.10" data-path="testing-between-groups.html"><a href="testing-between-groups.html#activity-6---undertaking-an-independent-samples-t-test"><i class="fa fa-check"></i><b>6.10</b> Activity 6 - Undertaking an independent samples t-test</a></li>
<li class="chapter" data-level="6.11" data-path="testing-between-groups.html"><a href="testing-between-groups.html#writing-up-results-and-conclusions-1"><i class="fa fa-check"></i><b>6.11</b> Writing up results and conclusions</a></li>
<li class="chapter" data-level="6.12" data-path="testing-between-groups.html"><a href="testing-between-groups.html#you-are-free-4"><i class="fa fa-check"></i><b>6.12</b> You are Free!</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="you-got-the-power.html"><a href="you-got-the-power.html"><i class="fa fa-check"></i><b>7</b> You got the power !</a>
<ul>
<li class="chapter" data-level="7.1" data-path="you-got-the-power.html"><a href="you-got-the-power.html#checking-installation-and-loading-packages-4"><i class="fa fa-check"></i><b>7.1</b> Checking installation and loading packages</a></li>
<li class="chapter" data-level="7.2" data-path="you-got-the-power.html"><a href="you-got-the-power.html#key-power-facts"><i class="fa fa-check"></i><b>7.2</b> Key power facts:</a></li>
<li class="chapter" data-level="7.3" data-path="you-got-the-power.html"><a href="you-got-the-power.html#simulating-sample-sizes"><i class="fa fa-check"></i><b>7.3</b> Simulating sample sizes</a></li>
<li class="chapter" data-level="7.4" data-path="you-got-the-power.html"><a href="you-got-the-power.html#installing-and-loading-new-packages-we-will-be-using-today"><i class="fa fa-check"></i><b>7.4</b> Installing and loading new packages we will be using today</a></li>
<li class="chapter" data-level="7.5" data-path="you-got-the-power.html"><a href="you-got-the-power.html#activity-1---simulating-data"><i class="fa fa-check"></i><b>7.5</b> Activity 1 - Simulating data</a></li>
<li class="chapter" data-level="7.6" data-path="you-got-the-power.html"><a href="you-got-the-power.html#activity-2---conducting-t-tests-and-effect-sizes."><i class="fa fa-check"></i><b>7.6</b> Activity 2 - Conducting t tests and effect sizes.</a></li>
<li class="chapter" data-level="7.7" data-path="you-got-the-power.html"><a href="you-got-the-power.html#activity-3---plotting-our-simulated-data"><i class="fa fa-check"></i><b>7.7</b> Activity 3 - Plotting our simulated data</a></li>
<li class="chapter" data-level="7.8" data-path="you-got-the-power.html"><a href="you-got-the-power.html#power-analysis-in-r"><i class="fa fa-check"></i><b>7.8</b> Power analysis in R</a></li>
<li class="chapter" data-level="7.9" data-path="you-got-the-power.html"><a href="you-got-the-power.html#power-analysis-on-correlations"><i class="fa fa-check"></i><b>7.9</b> Power analysis on correlations</a></li>
<li class="chapter" data-level="7.10" data-path="you-got-the-power.html"><a href="you-got-the-power.html#activity-4---conducting-a-power-analysis-for-a-t-test"><i class="fa fa-check"></i><b>7.10</b> Activity 4 - Conducting a power analysis for a t-test</a></li>
<li class="chapter" data-level="7.11" data-path="you-got-the-power.html"><a href="you-got-the-power.html#writing-up-a-power-analysis"><i class="fa fa-check"></i><b>7.11</b> Writing up a power analysis</a></li>
<li class="chapter" data-level="7.12" data-path="you-got-the-power.html"><a href="you-got-the-power.html#you-are-free-5"><i class="fa fa-check"></i><b>7.12</b> You are Free!</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="correlation-in-r.html"><a href="correlation-in-r.html"><i class="fa fa-check"></i><b>8</b> Correlation in R</a>
<ul>
<li class="chapter" data-level="8.1" data-path="correlation-in-r.html"><a href="correlation-in-r.html#checking-installation-and-loading-packages-5"><i class="fa fa-check"></i><b>8.1</b> Checking installation and loading packages</a></li>
<li class="chapter" data-level="8.2" data-path="correlation-in-r.html"><a href="correlation-in-r.html#investigating-correlational-relationships"><i class="fa fa-check"></i><b>8.2</b> Investigating correlational relationships</a></li>
<li class="chapter" data-level="8.3" data-path="correlation-in-r.html"><a href="correlation-in-r.html#activity-1---formulate-your-research-question-1"><i class="fa fa-check"></i><b>8.3</b> Activity 1 - Formulate your research question</a></li>
<li class="chapter" data-level="8.4" data-path="correlation-in-r.html"><a href="correlation-in-r.html#activity-2---how-much-political-attitude"><i class="fa fa-check"></i><b>8.4</b> Activity 2 - How much political attitude?</a></li>
<li class="chapter" data-level="8.5" data-path="correlation-in-r.html"><a href="correlation-in-r.html#activity-3---looking-for-straight-lines"><i class="fa fa-check"></i><b>8.5</b> Activity 3 - looking for straight lines</a></li>
<li class="chapter" data-level="8.6" data-path="correlation-in-r.html"><a href="correlation-in-r.html#conducting-correlations"><i class="fa fa-check"></i><b>8.6</b> Conducting correlations</a></li>
<li class="chapter" data-level="8.7" data-path="correlation-in-r.html"><a href="correlation-in-r.html#writing-up-results-and-conclusions-2"><i class="fa fa-check"></i><b>8.7</b> Writing up results and conclusions</a></li>
<li class="chapter" data-level="8.8" data-path="correlation-in-r.html"><a href="correlation-in-r.html#activity-4---exploring-the-data"><i class="fa fa-check"></i><b>8.8</b> Activity 4 - Exploring the data</a></li>
<li class="chapter" data-level="8.9" data-path="correlation-in-r.html"><a href="correlation-in-r.html#writing-up-results-and-conclusions-3"><i class="fa fa-check"></i><b>8.9</b> Writing up results and conclusions</a></li>
<li class="chapter" data-level="8.10" data-path="correlation-in-r.html"><a href="correlation-in-r.html#you-are-free-6"><i class="fa fa-check"></i><b>8.10</b> You are Free!</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html"><i class="fa fa-check"></i><b>9</b> Linear regression in R</a>
<ul>
<li class="chapter" data-level="9.1" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html#checking-installation-and-loading-packages-6"><i class="fa fa-check"></i><b>9.1</b> Checking installation and loading packages</a></li>
<li class="chapter" data-level="9.2" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html#investigating-linear-regressions"><i class="fa fa-check"></i><b>9.2</b> Investigating linear regressions</a></li>
<li class="chapter" data-level="9.3" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html#activity-1---formulate-your-research-question-2"><i class="fa fa-check"></i><b>9.3</b> Activity 1 - Formulate your research question</a></li>
<li class="chapter" data-level="9.4" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html#linear-regression-in-r-1"><i class="fa fa-check"></i><b>9.4</b> Linear regression in R</a></li>
<li class="chapter" data-level="9.5" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html#writing-up-results-and-conclusions-4"><i class="fa fa-check"></i><b>9.5</b> Writing up results and conclusions</a></li>
<li class="chapter" data-level="9.6" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html#plotting-our-results-1"><i class="fa fa-check"></i><b>9.6</b> Plotting our results</a></li>
<li class="chapter" data-level="9.7" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html#activity-2---plotting-straight-lines"><i class="fa fa-check"></i><b>9.7</b> Activity 2 - Plotting straight lines</a></li>
<li class="chapter" data-level="9.8" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html#you-are-free-7"><i class="fa fa-check"></i><b>9.8</b> You are Free!</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">UNSW PSYC2001 Computing Tutorials</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="testing-our-first-hypothesis" class="section level1 hasAnchor" number="5">
<h1><span class="header-section-number">Chapter 5</span> Testing our first hypothesis<a href="testing-our-first-hypothesis.html#testing-our-first-hypothesis" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Today we are going to ask our first question and seek an answer from the data. We will get the data into shape so that it is in the right format for visualizing and analysing. Then we will run the analysis and learn the answer to our question. Welcome. You are now a psychologist :)</p>
<div id="checking-installation-and-loading-packages-2" class="section level2 hasAnchor" number="5.1">
<h2><span class="header-section-number">5.1</span> Checking installation and loading packages<a href="testing-our-first-hypothesis.html#checking-installation-and-loading-packages-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>As usual we first always check and load in our required packages. Amend the code in
your script so that it matches the code below. Then make sure it runs just fine.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="testing-our-first-hypothesis.html#cb1-1" tabindex="-1"></a><span class="co"># Check if packages are installed, if not install.</span></span>
<span id="cb1-2"><a href="testing-our-first-hypothesis.html#cb1-2" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(here)) <span class="fu">install.packages</span>(<span class="st">&#39;here&#39;</span>) <span class="co">#checks if a package is installed and installs it if required.</span></span>
<span id="cb1-3"><a href="testing-our-first-hypothesis.html#cb1-3" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(tidyverse)) <span class="fu">install.packages</span>(<span class="st">&#39;tidyverse&#39;</span>)</span>
<span id="cb1-4"><a href="testing-our-first-hypothesis.html#cb1-4" tabindex="-1"></a></span>
<span id="cb1-5"><a href="testing-our-first-hypothesis.html#cb1-5" tabindex="-1"></a><span class="fu">library</span>(here) <span class="co">#loads in the specified package</span></span>
<span id="cb1-6"><a href="testing-our-first-hypothesis.html#cb1-6" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
</div>
<div id="developing-our-hypotheses" class="section level2 hasAnchor" number="5.2">
<h2><span class="header-section-number">5.2</span> Developing our hypotheses<a href="testing-our-first-hypothesis.html#developing-our-hypotheses" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Today we are going to address one of the key questions of the study about social media use – how does mood influence active social media use? Active social media use involves interacting with content (i.e. liking posts) rather than just observing posts.</p>
<p>There is some evidence to suggest that passive social media use is associated with lower mood in adolescents, whereas active social media use is related to positive mood <a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC7366938/">Dienlin &amp; Johannes, 2020</a>. However, a lot of the existing evidence comes from self-report, rather than measuring social media behaviour directly.</p>
<p>To address this question, the researchers used the participants’ metadata to count how frequently they liked posts. By cross-referencing this with the mood diary kept by each participant, they were able to calculate the average number of likes per 10 minutes of use when participants were in a good mood, and when they were in a bad mood.</p>
<p>It should be clear by now that we will be addressing this question using the <code>good_mood_likes</code> and <code>bad_mood_likes</code> varaibles. Remember, these variables stand for the following:</p>
<ul>
<li><code>good_mood_likes</code> – average number of likes made over 10 min during a good mood (from platform + diary)</li>
<li><code>bad_mood_likes</code> – as above, but during bad mood</li>
</ul>
<p>But you should know this, because you read the README.txt file already, right? :)</p>
<div id="activity---defining-our-hypotheses" class="section level3 hasAnchor" number="5.2.1">
<h3><span class="header-section-number">5.2.1</span> Activity - Defining our hypotheses<a href="testing-our-first-hypothesis.html#activity---defining-our-hypotheses" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Based on the information above, discuss and formulate hypotheses around the following:</p>
<ol style="list-style-type: decimal">
<li>Should there be a difference in the number of likes between the mood conditions</li>
<li>What direction do you think this difference could be? Can you formulate an experimental hypothesis each way – i.e. good mood likes &gt; bad mood likes, and vice versa?</li>
<li>What is the null hypothesis?</li>
</ol>
<div style="border-left: 4px solid #9C27B0; background-color: #F3E5F5; padding: 10px; margin: 10px 0;">
<p><strong>Question:</strong> Discuss this with your neighbour and your tutor. Make sure you have clearly defined your hypotheses before moving forward.</p>
</div>
</div>
</div>
<div id="visualising-our-data" class="section level2 hasAnchor" number="5.3">
<h2><span class="header-section-number">5.3</span> Visualising our data<a href="testing-our-first-hypothesis.html#visualising-our-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We may have mentioned before that it’s incredibly important to visualize your data before running any statistical tests. This is because visualizing your data can help you understand the underlying distribution of the data, identify any potential outliers or anomalies, and ensure that the assumptions of the statistical test you plan to use are met. Remember, it protects against “garbage in, garbage out”!</p>
<div id="activity---loading-in-the-data" class="section level3 hasAnchor" number="5.3.1">
<h3><span class="header-section-number">5.3.1</span> Activity - Loading in the data<a href="testing-our-first-hypothesis.html#activity---loading-in-the-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Last lab we were very smart and saved the cleaned version of the data as a new CSV file. This is what we will be using today. We put it in the Data folder for you already. Use the Files pane to check.</p>
<p>First step! Let’s load the dataset <code>PSYC2001_social-media-data-cleaned.csv</code>. To do this we use the same <code>read.csv()</code> function combined with <code>here()</code>. Do you remember how to do this?</p>
<p>Complete the following line of code in your script. Again, we have been cheeky and have left a little bit out. But you should be able to work it out. You can also refer back to Section <a href="data-wrangling-and-visualisation.html#sec-import-data">3.5.1</a> if you need to.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="testing-our-first-hypothesis.html#cb2-1" tabindex="-1"></a>social_media <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="at">file =</span> <span class="fu">here</span>(,<span class="st">&quot;PSYC2001_social-media-data-cleaned.csv&quot;</span>)) <span class="co">#reads in CSV files</span></span></code></pre></div>
<p>Now, we did save the data ourselves last week, so we know it is clean. But just to be sure, amend your script so you can get a summary of the data using the <code>summary()</code> function. If you don’t remember how to do this, then you can check what happened in Section <a href="data-wrangling-and-visualisation.html#sec-data-view">3.6.1</a>.</p>
<p>Before we conduct any kind of statistical test it is a good idea to see how it looks. This will give us an understanding about the underlying data that is driving the results of our statistical test.</p>
<div style="border-left: 4px solid #FF9800; background-color: #FFF3E0; padding: 10px; margin: 10px 0;">
<p><strong>Warning:</strong> It is generally <strong>bad practice</strong> to go straight from the raw data to the results of a statistical test without first visualising the data.</p>
</div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-4"></span>
<img src="images/Testing_our_first_hypothesis/Statistics_professors_reaction.gif" alt="Professors reaction when you don't visualise data" width="50%" />
<p class="caption">
Figure 5.1: Professors reaction when you don’t visualise data
</p>
</div>
</div>
</div>
<div id="density-plots-are-useful-and-pretty" class="section level2 hasAnchor" number="5.4">
<h2><span class="header-section-number">5.4</span> Density plots are useful (and pretty)<a href="testing-our-first-hypothesis.html#density-plots-are-useful-and-pretty" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We can look at the distribution of the data using a density plot. A density plot is a smoothed version of a histogram which allows us to understand what the full distribution might look like if we had all the data in the world. More information on that <a href="https://www.data-to-viz.com/graph/density.html">is here</a> if you are interested !</p>
<p>In order to make this easy to plot we first have to wrangle our data a bit. Remember, data analysis is 90% wrangling, 10% analysis! What we want to do here is convert our data from a wide-format (which is more digestible for us mere humans) into a long format (which programs like R generally like more!). You can read more on that <a href="https://www.statology.org/long-vs-wide-data/">here</a>, but to make it simple, we just need to get the key variables from our data that currently look like this:</p>
<p><strong>Wideform data</strong></p>
<pre><code>##   id good_mood_likes bad_mood_likes
## 1 S1            22.8           46.5
## 2 S2            46.0           48.3
## 3 S3            50.8           46.1
## 4 S4            29.9           29.2
## 5 S5            37.1           52.4
## 6 S6            26.9           20.2</code></pre>
<p>And convert it into a long format that looks like this:</p>
<pre><code>## # A tibble: 6 × 3
##   id    mood            likes
##   &lt;chr&gt; &lt;chr&gt;           &lt;dbl&gt;
## 1 S1    good_mood_likes  22.8
## 2 S1    bad_mood_likes   46.5
## 3 S2    good_mood_likes  46  
## 4 S2    bad_mood_likes   48.3
## 5 S3    good_mood_likes  50.8
## 6 S3    bad_mood_likes   46.1</code></pre>
<p>As you can see, instead of having each subject’s good and bad mood likes in separate columns, we now have a single column for likes and a second column which indicates whether the likes were made in a good or bad mood. So each subject now has two rows in the dataset. This makes it much easier to plot, and to do many other things!</p>
<div id="activity---get-back-on-the-pipes" class="section level3 hasAnchor" number="5.4.1">
<h3><span class="header-section-number">5.4.1</span> Activity - Get back on the pipes!<a href="testing-our-first-hypothesis.html#activity---get-back-on-the-pipes" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Its time to get back on the pipes!
The below code gets our data into longform by taking the following steps:</p>
<ul>
<li>First we use the <code>select()</code> function to easily choose which columns we do (or don’t) want to keep in our dataframe.</li>
<li>Second we use the <code>pivot_longer()</code> function which allows us to combine different columns together. Both of these functions come from the <code>tidyverse</code> package.</li>
<li>In the code below we take the columns ending with “likes” and put their values (i.e the number of likes) into the column “likes” and their column names names (i.e good or bad mood) into the column “mood”.</li>
</ul>
<p>Highlight and run this code in your script to get the data into longform.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="testing-our-first-hypothesis.html#cb5-1" tabindex="-1"></a>social_media_likes <span class="ot">&lt;-</span> social_media <span class="sc">%&gt;%</span> </span>
<span id="cb5-2"><a href="testing-our-first-hypothesis.html#cb5-2" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">&quot;id&quot;</span>,<span class="st">&quot;good_mood_likes&quot;</span>,<span class="st">&quot;bad_mood_likes&quot;</span>) <span class="sc">%&gt;%</span> <span class="co"># choose which columns we want keep in our dataframe</span></span>
<span id="cb5-3"><a href="testing-our-first-hypothesis.html#cb5-3" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">ends_with</span>(<span class="st">&quot;likes&quot;</span>), <span class="at">names_to =</span> <span class="st">&quot;mood&quot;</span>, <span class="at">values_to =</span> <span class="st">&quot;likes&quot;</span>) <span class="co">#take columns ending with &quot;likes&quot; and move the column names into &quot;mood&quot; and column values into &quot;likes&quot;</span></span></code></pre></div>
<p>Note that we have saved this changed data as a new object called <code>social_media_likes</code>.</p>
<p>Let’s make sure that this data still looks okay by using the <code>head()</code> function. Complete the code in your script so that it looks exactly like below</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="testing-our-first-hypothesis.html#cb6-1" tabindex="-1"></a><span class="fu">head</span>(social_media_likes)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 3
##   id    mood            likes
##   &lt;chr&gt; &lt;chr&gt;           &lt;dbl&gt;
## 1 S1    good_mood_likes  22.8
## 2 S1    bad_mood_likes   46.5
## 3 S2    good_mood_likes  46  
## 4 S2    bad_mood_likes   48.3
## 5 S3    good_mood_likes  50.8
## 6 S3    bad_mood_likes   46.1</code></pre>
<p>Et voila!</p>
</div>
<div id="activity---start-plotting" class="section level3 hasAnchor" number="5.4.2">
<h3><span class="header-section-number">5.4.2</span> Activity - start plotting<a href="testing-our-first-hypothesis.html#activity---start-plotting" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Now, we can get a density plot in R by using the <code>geom_density</code> function inside <code>ggplot()</code>.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="testing-our-first-hypothesis.html#cb8-1" tabindex="-1"></a>social_media_likes <span class="sc">%&gt;%</span> </span>
<span id="cb8-2"><a href="testing-our-first-hypothesis.html#cb8-2" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> likes, <span class="at">colour =</span> mood)) <span class="sc">+</span></span>
<span id="cb8-3"><a href="testing-our-first-hypothesis.html#cb8-3" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">linewidth =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb8-4"><a href="testing-our-first-hypothesis.html#cb8-4" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Number of likes&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Density&quot;</span>) <span class="sc">+</span></span>
<span id="cb8-5"><a href="testing-our-first-hypothesis.html#cb8-5" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="co">#themes can be provided to ggplot which give it a bunch of aesthetics to change. One of these is theme_classic</span></span></code></pre></div>
<p><img src="_main_files/figure-html/Create%20a%20density%20plot-1.png" width="672" /></p>
<div style="border-left: 4px solid #2196F3; background-color: #E7F3FE; padding: 10px; margin: 10px 0;">
<p><strong>Info:</strong> We are using a new function here called <code>theme_classic()</code>. This makes the graph look at a bit nicer. There are a bunch of other available themes <a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">here</a>. We also have a new argument <code>colour</code> inside the <code>aes()</code> function which tells <code>ggplot()</code> to use different line colours depending on the participants mood (i.e good or bad mood).</p>
</div>
</div>
</div>
<div id="activity-2---choosing-a-new-theme" class="section level2 hasAnchor" number="5.5">
<h2><span class="header-section-number">5.5</span> Activity 2 - Choosing a new theme<a href="testing-our-first-hypothesis.html#activity-2---choosing-a-new-theme" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Lets have a go at replicating the previous graph but using a new theme. You can pick whichever theme you think looks the best. Notice that changing the theme will only change non-data related aesthetic features of the graph.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="testing-our-first-hypothesis.html#cb9-1" tabindex="-1"></a>social_media_likes <span class="sc">%&gt;%</span> </span>
<span id="cb9-2"><a href="testing-our-first-hypothesis.html#cb9-2" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> likes, <span class="at">colour =</span> mood)) <span class="sc">+</span></span>
<span id="cb9-3"><a href="testing-our-first-hypothesis.html#cb9-3" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">linewidth =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb9-4"><a href="testing-our-first-hypothesis.html#cb9-4" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Number of likes&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Density&quot;</span>) <span class="sc">+</span></span>
<span id="cb9-5"><a href="testing-our-first-hypothesis.html#cb9-5" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="co">#themes can be provided to ggplot which give it a bunch of aesthetics to change. One of these is theme_classic</span></span></code></pre></div>
<p><img src="_main_files/figure-html/Activity%202%20-%20Changing%20ggplot%20themes-1.png" width="672" /></p>
</div>
<div id="descriptive-statistics" class="section level2 hasAnchor" number="5.6">
<h2><span class="header-section-number">5.6</span> Descriptive statistics<a href="testing-our-first-hypothesis.html#descriptive-statistics" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Before we can move onto conducting t-tests it is always a good idea to generate our descriptive statistics. For the data we are looking at <strong>the most relevant descriptive statistics are the mean and standard deviation</strong>. This is because we want to conduct a t-test to compare the average likes in different moods. We can easily get this information in R by using the <code>summarise()</code> function together with the <code>group_by()</code> function. The <code>group_by()</code> splits the data into different groups and the <code>summarise()</code> function calculates a statistic (i.e the mean and standard deviation). Both of these packages come from the <code>tidyverse</code> package.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="testing-our-first-hypothesis.html#cb10-1" tabindex="-1"></a>social_media_descriptives <span class="ot">&lt;-</span> social_media_likes <span class="sc">%&gt;%</span> </span>
<span id="cb10-2"><a href="testing-our-first-hypothesis.html#cb10-2" tabindex="-1"></a>  <span class="fu">group_by</span>(mood) <span class="sc">%&gt;%</span> <span class="co">#split the data by mood</span></span>
<span id="cb10-3"><a href="testing-our-first-hypothesis.html#cb10-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_likes =</span> <span class="fu">mean</span>(likes),</span>
<span id="cb10-4"><a href="testing-our-first-hypothesis.html#cb10-4" tabindex="-1"></a>            <span class="at">sd_likes =</span> <span class="fu">sd</span>(likes)) <span class="co">#calculate the mean number of likes</span></span>
<span id="cb10-5"><a href="testing-our-first-hypothesis.html#cb10-5" tabindex="-1"></a></span>
<span id="cb10-6"><a href="testing-our-first-hypothesis.html#cb10-6" tabindex="-1"></a><span class="fu">head</span>(social_media_descriptives)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 3
##   mood            mean_likes sd_likes
##   &lt;chr&gt;                &lt;dbl&gt;    &lt;dbl&gt;
## 1 bad_mood_likes        49.8     17.2
## 2 good_mood_likes       43.0     16.1</code></pre>
<div style="border-left: 4px solid #9C27B0; background-color: #F3E5F5; padding: 10px; margin: 10px 0;">
<p><strong>Question:</strong> What are the mean number of likes in each different mood ? What is the standard deviation ?</p>
</div>
</div>
<div id="activity-3---calculating-the-median-number-of-likes" class="section level2 hasAnchor" number="5.7">
<h2><span class="header-section-number">5.7</span> Activity 3 - Calculating the median number of likes<a href="testing-our-first-hypothesis.html#activity-3---calculating-the-median-number-of-likes" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Great ! We have the mean number of likes when subjects are in a good and bad mood. Please see if you are able to use these functions to instead calculate the median number of likes under different mood conditions.</p>
<div style="border-left: 4px solid #00bfa5; background-color: #e0f2f1; padding: 10px; margin: 10px 0;">
<strong>Hint:</strong> The <code>median()</code> function is used to calculate medians !
</div>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="testing-our-first-hypothesis.html#cb12-1" tabindex="-1"></a>social_media_median <span class="ot">&lt;-</span> social_media_likes <span class="sc">%&gt;%</span> </span>
<span id="cb12-2"><a href="testing-our-first-hypothesis.html#cb12-2" tabindex="-1"></a>  <span class="fu">group_by</span>(mood) <span class="sc">%&gt;%</span> <span class="co">#split the data by mood</span></span>
<span id="cb12-3"><a href="testing-our-first-hypothesis.html#cb12-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">median_likes =</span> <span class="fu">median</span>(likes)) <span class="co">#calculate the mean number of likes</span></span>
<span id="cb12-4"><a href="testing-our-first-hypothesis.html#cb12-4" tabindex="-1"></a></span>
<span id="cb12-5"><a href="testing-our-first-hypothesis.html#cb12-5" tabindex="-1"></a><span class="fu">head</span>(social_media_median)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 2
##   mood            median_likes
##   &lt;chr&gt;                  &lt;dbl&gt;
## 1 bad_mood_likes          49.3
## 2 good_mood_likes         45.9</code></pre>
</div>
<div id="testing-hypotheses-manually" class="section level2 hasAnchor" number="5.8">
<h2><span class="header-section-number">5.8</span> Testing hypotheses manually<a href="testing-our-first-hypothesis.html#testing-hypotheses-manually" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Now that we have had a look at the structure and descriptives statistics of our data we can have a go at using a t-test to compare the number of likes participants made in a good and bad mood. We could of course do this manually, by hand (as we have in the statistics tutorials). We have shown this below using the first 10 values for good and bad mood likes.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-7"></span>
<img src="https://github.com/BsoCool/UNSW-PSYC2001/blob/main/All%20images%20for%20computing%20tutorials/Testing_our_first_hypothesis/Manual%20t-test%20table.JPG?raw=true" alt="t-test table" width="75%" />
<p class="caption">
Figure 5.2: t-test table
</p>
</div>
<p>Thankfully, we have long since past the stone (pen) age so it is no longer necessary to do this by hand. We can get computers to do this for us!</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-8"></span>
<img src="https://github.com/BsoCool/UNSW-PSYC2001/blob/main/All%20images%20for%20computing%20tutorials/Testing_our_first_hypothesis/Space%20odyssey.gif?raw=true
" alt="Handwritten statistiscs be like" width="50%" />
<p class="caption">
Figure 5.3: Handwritten statistiscs be like
</p>
</div>
</div>
<div id="testing-hypothesis-using-a-two-sample-t-test" class="section level2 hasAnchor" number="5.9">
<h2><span class="header-section-number">5.9</span> Testing hypothesis using a two-sample t-test<a href="testing-our-first-hypothesis.html#testing-hypothesis-using-a-two-sample-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We can very easily calculate a t-test in R using the <code>t.test()</code> function which comes as part of <code>baseR</code>. Please first have a look at this function using the <code>?</code> syntax to understand its arguments. We recommend using the console from now on to do this rather than creating a codeblock.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-9"></span>
<img src="https://github.com/BsoCool/UNSW-PSYC2001/blob/main/All%20images%20for%20computing%20tutorials/Testing_our_first_hypothesis/Navigating%20to%20the%20Console.gif?raw=true" alt="Finding the Console" width="100%" />
<p class="caption">
Figure 5.4: Finding the Console
</p>
</div>
<p>We can see that <code>t.test()</code> takes different arguments which are important for the way it handles the data. What values you provide to these arguments is dependent on what kind of test you want to conduct. One of the most important arguments to fill in is the <code>paired</code> argument. This determines whether you are conducting an independent or paired samples t-test. Here, we have collected the number of likes for the same subject in different moods. This means this data comes from a repeated-measures design, and so a paired t-test is most appropriate. We also need to provide <code>t.test()</code> with a formula telling it what to do with our data. The left hand side is the numerical variable and the right hand side is a grouping variable.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="testing-our-first-hypothesis.html#cb14-1" tabindex="-1"></a><span class="co">#t.test(formula = likes ~ mood, data = social_media_likes, paired = TRUE)  #compute a t-test. Likes ~ mood indicates that likes is the numerical variable and mood is a grouping variables. Paired indicates whether to conduct a paired or independent t-test.</span></span></code></pre></div>
<div style="border-left: 4px solid #9C27B0; background-color: #F3E5F5; padding: 10px; margin: 10px 0;">
<p><strong>Question:</strong> Discuss the output of this paired t-test with your neighbour and tutors. What does it tell us ?</p>
</div>
</div>
<div id="activity-4---one-sample-t-tests" class="section level2 hasAnchor" number="5.10">
<h2><span class="header-section-number">5.10</span> Activity 4 - One-sample t-tests<a href="testing-our-first-hypothesis.html#activity-4---one-sample-t-tests" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Now that we have the output of a paired t-test we can compare it to a one sample t-test. The results of both of these tests should be identical (this has been covered in the lectures). For those that haven’t watched the lectures, this is because a paired t-test is basically a one-sample t-test of matched difference scores (<a href="https://statisticsbyjim.com/hypothesis-testing/t-tests-1-sample-2-sample-paired-t-tests/">more on that here</a>)</p>
<p>Are you able to conduct a one-sample t-test using R ?</p>
<p>First you will need to use the <code>mutate()</code> function on the original <code>social_media</code> dataframe to create a difference column.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="testing-our-first-hypothesis.html#cb15-1" tabindex="-1"></a>social_media_diff <span class="ot">&lt;-</span> social_media <span class="sc">%&gt;%</span> </span>
<span id="cb15-2"><a href="testing-our-first-hypothesis.html#cb15-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">likes_diff =</span> good_mood_likes <span class="sc">-</span> bad_mood_likes) <span class="co">#first try to create a new column which is the difference between mood likes</span></span>
<span id="cb15-3"><a href="testing-our-first-hypothesis.html#cb15-3" tabindex="-1"></a></span>
<span id="cb15-4"><a href="testing-our-first-hypothesis.html#cb15-4" tabindex="-1"></a><span class="fu">head</span>(social_media_diff)</span></code></pre></div>
<pre><code>##   X id  age time_on_social urban good_mood_likes bad_mood_likes followers polit_informed
## 1 1 S1 15.2           3.06     1            22.8           46.5     173.3            2.3
## 2 2 S2 16.0           2.18     1            46.0           48.3     144.3            1.6
## 3 3 S3 16.8           1.92     1            50.8           46.1      76.5            1.9
## 4 4 S4 15.6           2.61     1            29.9           29.2     171.7            1.6
## 5 5 S5 17.1           3.24     1            37.1           52.4     109.5            2.0
## 6 6 S6 15.7           2.44     1            26.9           20.2     157.5            2.4
##   polit_campaign polit_activism likes_diff
## 1            3.2            3.6      -23.7
## 2            2.2            2.6       -2.3
## 3            2.7            3.0        4.7
## 4            2.3            2.6        0.7
## 5            2.9            3.3      -15.3
## 6            3.4            3.9        6.7</code></pre>
<p>Once we have correctly calculated our difference score we can use the <code>t.test()</code> function to get our results.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="testing-our-first-hypothesis.html#cb17-1" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">formula =</span> likes_diff<span class="sc">~</span><span class="dv">1</span>, <span class="at">data =</span> social_media_diff) <span class="co">#the formula likes_diff~1 indicates that there is no grouping variables (i.e just compare to 0!)</span></span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  likes_diff
## t = -3.336, df = 59, p-value = 0.001474
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  -10.881375  -2.721958
## sample estimates:
## mean of x 
## -6.801667</code></pre>
<div style="border-left: 4px solid #2196F3; background-color: #E7F3FE; padding: 10px; margin: 10px 0;">
<p><strong>Info:</strong> The right hand side of the formula ‘likes_diff~<strong>1</strong>’ indicates that there is no grouping variable.</p>
</div>
<div style="border-left: 4px solid #9C27B0; background-color: #F3E5F5; padding: 10px; margin: 10px 0;">
<p><strong>Question:</strong> Compare the output of the one-sample t-test and the paired t-test. Are they the same ?</p>
</div>
</div>
<div id="writing-up-results-and-conclusions" class="section level2 hasAnchor" number="5.11">
<h2><span class="header-section-number">5.11</span> Writing up results and conclusions<a href="testing-our-first-hypothesis.html#writing-up-results-and-conclusions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Let’s have a go at writing up the results of the paired samples t-test we have conducted in APA format. While it is not necessarily critical to use APA formatting outside of these psychology courses, it is important to follow some existing format so that readers can easily interpret your results and conclusions about important data.</p>
<div style="border-left: 4px solid #8B5E3C; background-color: #F5F5DC; padding: 10px; margin: 10px 0;">
<p><strong>Results:</strong> A paired samples t-test indicated that the number of likes was greater when participants were in a bad mood (M = 49.8 , SD = 17.2) than in a good mood (M = 43.0 , SD = 16.1) and this difference was statistically significant (t(59) = 3.336, p = 0.001).</p>
</div>
<p>What can we conclude from this? Please have a go at writing this up.</p>
<div style="border-left: 4px solid #8B5E3C; background-color: #F5F5DC; padding: 10px; margin: 10px 0;">
<p><strong>Conclusions:</strong> Your conclusion will go here !</p>
</div>
</div>
<div id="plotting-our-results" class="section level2 hasAnchor" number="5.12">
<h2><span class="header-section-number">5.12</span> Plotting our results<a href="testing-our-first-hypothesis.html#plotting-our-results" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Now that we have conducted our statistical test we need to present the results in the simplest way possible. One way to do this is by using the average number of likes when participants are in a good and bad mood and plotting it using a column graph.</p>
</div>
<div id="activity-5---plotting-the-mean-number-of-likes" class="section level2 hasAnchor" number="5.13">
<h2><span class="header-section-number">5.13</span> Activity 5 - Plotting the mean number of likes<a href="testing-our-first-hypothesis.html#activity-5---plotting-the-mean-number-of-likes" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Are you able to plot the mean number of likes as a column graph ?</p>
<div style="border-left: 4px solid #00bfa5; background-color: #e0f2f1; padding: 10px; margin: 10px 0;">
<p><strong>Hint:</strong> This will be very similar to the code used to plot the density graph but instead using <code>geom_col()</code>.</p>
</div>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="testing-our-first-hypothesis.html#cb19-1" tabindex="-1"></a>social_media_descriptives <span class="sc">%&gt;%</span>   <span class="co">#write code that produces a column graph of likes with a different colour for each mood</span></span>
<span id="cb19-2"><a href="testing-our-first-hypothesis.html#cb19-2" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">y =</span> mean_likes, <span class="at">x =</span> mood, <span class="at">fill =</span> mood)) <span class="sc">+</span></span>
<span id="cb19-3"><a href="testing-our-first-hypothesis.html#cb19-3" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">linewidth =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb19-4"><a href="testing-our-first-hypothesis.html#cb19-4" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">&quot;Number of likes&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Mood&quot;</span>)<span class="sc">+</span></span>
<span id="cb19-5"><a href="testing-our-first-hypothesis.html#cb19-5" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/Activity%205-1.png" width="672" /></p>
</div>
<div id="you-are-free-3" class="section level2 hasAnchor" number="5.14">
<h2><span class="header-section-number">5.14</span> You are Free!<a href="testing-our-first-hypothesis.html#you-are-free-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Well done you have finished for this week! There is no extension activity this week so if you have finished please confirm that you understand everything with your tutor.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-10"></span>
<img src="https://github.com/BsoCool/UNSW-PSYC2001/blob/main/All%20images%20for%20computing%20tutorials/Testing_our_first_hypothesis/Students%20leaving.gif?raw=true" alt="Students leaving evil statistics classes" width="50%" />
<p class="caption">
Figure 5.5: Students leaving evil statistics classes
</p>
</div>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="what-is-the-sampling-distribution-of-the-mean.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="testing-between-groups.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/Testing_our_first_hypothesis.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section",
"scroll_highlight": true
}
});
});
</script>

</body>

</html>
